project_name: deletify
machines:
  # for Debian Family
  - user: ub64 # required
    pass: ub64 # required
    port: 5590 # required
    private_ip: "192.168.16.17" # required
    # root_pass: <root-pass> # default: root
    # passwd_auth: <yes-or-no> # default: no
    # ram: <ram> # default: 1024
    # cpus: <processors> # default: 1
    # disk_size: <size> # default: 10GB
    # box: <box-name> # default: ubuntu/bionic64

  # for RedHat Family
  # - user: redhat # required
  #   pass: redhat # required
  #   port: 5591 # required
  #   private_ip: "192.168.16.19" # required
  #   # root_pass: <root-pass> # default: root
  #   # passwd_auth: <yes-or-no> # default: no
  #   # ram: <ram> # default: 1024
  #   # cpus: <processors> # default: 1
  #   disk_size: 40GB # default: 10GB
  #   box: centos/7 # default: ubuntu/bionic64
